package:
  name: q2-metadata
  version: {{ PLUGIN_VERSION }}
source:
  path: ..
build:
  script: make install
requirements:
  host:
  - python {{ python }}
  - setuptools
  - versioningit
  - wheel
  run:
  - python {{ python }}
  - numpy
  - scipy {{ scipy }}
  - pandas {{ pandas }}
  - scikit-bio {{ scikit_bio }}
  - qiime2 >={{ qiime2 }}
  - q2templates >={{ q2templates }}
  - q2-types >={{ q2_types }}
  build:
  - python {{ python }}
  - setuptools
  - versioningit
test:
  requires:
  - qiime2 >={{ qiime2 }}
  - q2templates >={{ q2templates }}
  - q2-types >={{ q2_types }}
  - pytest
  imports:
  - q2_metadata
  - qiime2.plugins.metadata
  commands:
  - py.test --pyargs q2_metadata
about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
